apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.secret.name" . }}
type: Opaque
data:
  rootUser: {{ .Values.credentials.rootUser | default "root" | b64enc | quote }}
  {{- if .Values.credentials.rootPassword }}
  rootPassword: {{ .Values.credentials.rootPassword | b64enc | quote }}      
  {{- else }}
  rootPassword: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  username: {{ .Values.credentials.username | default "maria" | b64enc | quote }}
  {{- if .Values.credentials.password }}
  password: {{ .Values.credentials.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}