apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb.service.name" . }}
spec:
  selector:
    app: {{ include "mariadb.fullname" . }}
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
