apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      {{- if .Values.serviceAccount }}
      serviceAccountName: {{ include "mongodb-helm.ServiceAccountName" . }}
      {{- end }}
      containers:
        - name: mongodb
          image: {{ .Values.image }}
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongodb-auth
                  key: adminUsername
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongodb-auth
                  key: adminPassword
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongodb-auth
                  key: rwUsername
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongodb-auth
                  key: rwPassword
          volumeMounts:
            - name: {{ .Release.Name }}-persistent-storage
              mountPath: /data/db
      volumes:
        - name: {{ .Release.Name }}-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mongodb-pvc
