apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mongodb-init-script
data:
  init.sh: |
    #!/bin/bash
    mongo -u {{ .Values.credentials.adminUsername }} -p {{ .Values.credentials.adminPassword }} --authenticationDatabase admin --eval "
    db.createUser({
      user: '{{ .Values.credentials.rwUsername }}',
      pwd: '{{ .Values.credentials.rwPassword }}',
      roles: [{ role: 'readWrite', db: '{{ .Values.credentials.rwUsername }}' }]
    })"
