{{- if and .Values.serviceAccount .Values.roleBinding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-mongodb-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-mongodb-role
subjects:
  - kind: ServiceAccount
    name: {{ include "mongodb-helm.ServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}