apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-auth
type: Opaque
data:
  adminUsername: {{ default "" .Values.credentials.adminUsername | b64enc | quote }}
  adminPassword: {{ default "" .Values.credentials.adminPassword | b64enc | quote }}
  rwUsername: {{ default "" .Values.credentials.rwUsername | b64enc | quote }}
  rwPassword: {{ default "" .Values.credentials.rwPassword | b64enc | quote }}
